name: Build & Test
on:
  push:
    branches:
      - '!main'
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  build-backend:
    name: Build & Test Go Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          go version
          go mod tidy
      - name: Build
        run: go build .
      - name: Test
        run: go test -v .
      - name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

  build-deploy:
    name: Validate Deploy Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: false
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
  release-version:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == 'true'
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
