name: Deploy
on:
  release:
    types: [published, released]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deploy
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get Go package
        uses: dsaltares/fetch-gh-release-asset@0.06
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: "main"
          target: "backend/main"
          version: ${GITHUB_REF}
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approved


